# https://docs.docker.com/compose/compose-file/
version: "2.0"

services:
  mensa-microservice:
    container_name: mensa-microservice
    privileged: true
    build:
      context: ./
    restart: always
    networks:
      - web
    expose:
      - 8000
    volumes:
      - .:/app

networks:
  web:
    external: true
